services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2025.02.6
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
    environment:
      WEBPASSWORD: ${ADMIN_PASSWORD}
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      FTLCONF_LOCAL_IPV4: ${IPV4_HOST_ADDRESS}
      # Set "Listen on all interfaces, permit all origins"
      DNSMASQ_LISTENING: all
    volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - './etc-pihole:/etc/pihole'
    - './etc-dnsmasq.d:/etc/dnsmasq.d'
    - './hosts:/etc/hosts:ro'
    restart: unless-stopped
